[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/anime"
  to = "/anime.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/catalog"
  to = "/catalog.html"
  status = 200

[[redirects]]
  from = "/account"
  to = "/account.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200
